defaults:
  - _self_

hydra:
  run:
    dir: outputs/validation/${now:%Y-%m-%d_%H-%M-%S}

dataset:
  path: "validation_questions/validation_set_1.jsonl"
  limit: null  # Limit the number of examples to evaluate (null for all)
  question_type:  # Which type/modality to include in the evaluation
  - text-only
  - multi-to-text
  - image-to-text

grader:
  enabled: true
  model_name: gemini-3-flash-preview
  backend: google
  generate_config:
    reasoning_effort: minimal
